export interface Customer {
  customerName: string;
  company: string;
  phoneNumber: string;
  email: string;
  country: string;
  status: "Active" | "Inactive";
}

export const CUSTOMERS: Customer[] = [
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Floyd Miles",
    company: "Yahoo",
    phoneNumber: "(205) 555-0100",
    email: "floyd@yahoo.com",
    country: "Kiribati",
    status: "Inactive",
  },
  {
    customerName: "Ronald Richards",
    company: "Adobe",
    phoneNumber: "(302) 555-0107",
    email: "ronald@adobe.com",
    country: "Israel",
    status: "Inactive",
  },
  {
    customerName: "Marvin McKinney",
    company: "Tesla",
    phoneNumber: "(252) 555-0126",
    email: "marvin@tesla.com",
    country: "Iran",
    status: "Active",
  },
  {
    customerName: "Jerome Bell",
    company: "Google",
    phoneNumber: "(629) 555-0129",
    email: "jerome@google.com",
    country: "Réunion",
    status: "Active",
  },
  {
    customerName: "Kathryn Murphy",
    company: "Microsoft",
    phoneNumber: "(406) 555-0120",
    email: "kathryn@microsoft.com",
    country: "Curaçao",
    status: "Active",
  },
  {
    customerName: "Jacob Jones",
    company: "Yahoo",
    phoneNumber: "(208) 555-0112",
    email: "jacob@yahoo.com",
    country: "Brazil",
    status: "Active",
  },
  {
    customerName: "Kristin Watson",
    company: "Facebook",
    phoneNumber: "(704) 555-0127",
    email: "kristin@facebook.com",
    country: "Åland Islands",
    status: "Inactive",
  },

  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },

  {
    customerName: "John Doe",
    company: "Doe Enterprises",
    phoneNumber: "+1-202-555-0171",
    email: "john.doe@doeenterprises.com",
    country: "United States",
    status: "Active",
  },
  {
    customerName: "Anna Smith",
    company: "Smith Solutions",
    phoneNumber: "+44-20-7946-0958",
    email: "anna.smith@smithsolutions.co.uk",
    country: "United Kingdom",
    status: "Inactive",
  },
  {
    customerName: "Hans Müller",
    company: "Müller Tech",
    phoneNumber: "+49-30-1234567",
    email: "hans.mueller@muellertech.de",
    country: "Germany",
    status: "Active",
  },
  {
    customerName: "Maria Garcia",
    company: "Garcia Corp",
    phoneNumber: "+34-91-1234567",
    email: "maria.garcia@garciacorp.es",
    country: "Spain",
    status: "Inactive",
  },
  {
    customerName: "Li Wei",
    company: "Wei Enterprises",
    phoneNumber: "+86-10-12345678",
    email: "li.wei@weienterprises.cn",
    country: "China",
    status: "Active",
  },
  {
    customerName: "Yuki Tanaka",
    company: "Tanaka Industries",
    phoneNumber: "+81-3-1234-5678",
    email: "yuki.tanaka@tanakaindustries.jp",
    country: "Japan",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
  {
    customerName: "Olivia Martinez",
    company: "Martinez & Co",
    phoneNumber: "+52-55-1234-5678",
    email: "olivia.martinez@martinezco.mx",
    country: "Mexico",
    status: "Active",
  },
  {
    customerName: "Ravi Kumar",
    company: "Kumar Consulting",
    phoneNumber: "+91-22-12345678",
    email: "ravi.kumar@kumarconsulting.in",
    country: "India",
    status: "Inactive",
  },
  {
    customerName: "Emma Dupont",
    company: "Dupont Services",
    phoneNumber: "+33-1-23456789",
    email: "emma.dupont@dupontservices.fr",
    country: "France",
    status: "Active",
  },
  {
    customerName: "Carlos Oliveira",
    company: "Oliveira Trading",
    phoneNumber: "+55-11-1234-5678",
    email: "carlos.oliveira@oliveiratrading.br",
    country: "Brazil",
    status: "Inactive",
  },
];
