import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Sidebar } from '@/components/common';
import { Header } from '@/components/common/Header/Header';
import { USER } from '@/constants';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout_wrapper">
          <Sidebar />
          <Header />
          <main className="main">
            <h2 className="greetings">Hello {USER.name} 👋🏼,</h2>
            <div className="main-content">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
